# Generated by Django 5.0.4 on 2024-04-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='donor',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='donor',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
