# Generated by Django 5.0.4 on 2024-04-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_alter_donor_options_alter_donor_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
