# Generated by Django 5.0.4 on 2024-04-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_alter_donor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='role',
            field=models.CharField(default='donor', editable=False, max_length=10),
        ),
    ]
