# Generated by Django 5.0.4 on 2024-04-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_alter_owner_id'),
        ('donation', '0003_donation_charity_alter_donation_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='charity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='donations', to='charity.charity'),
        ),
    ]
