# Generated by Django 5.0.4 on 2024-04-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_alter_charity_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={},
        ),
        migrations.AlterModelManagers(
            name='owner',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
    ]
