# Generated by Django 5.0.4 on 2024-04-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_alter_owner_options_alter_owner_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
