# Generated by Django 5.0.4 on 2024-04-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_alter_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='role',
            field=models.CharField(default='owner', editable=False, max_length=10, unique=True),
        ),
    ]
