# Generated by Django 5.0.4 on 2024-04-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_owner_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='role',
            field=models.CharField(default='owner', editable=False, max_length=10),
        ),
    ]
