# Generated by Django 5.0.4 on 2024-04-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0008_alter_owner_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='owner_avatars/'),
        ),
    ]
