# Generated by Django 5.0.4 on 2024-04-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0009_alter_charity_name_alter_owner_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='owner_avatars'),
        ),
    ]
