# Generated by Django 5.0.4 on 2024-04-26 11:30

import charity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_alter_owner_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=charity.models.upload_path),
        ),
        migrations.AlterField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=charity.models.upload_path),
        ),
    ]
